#!/bin/bash
# PetalHop Egress Firewall
# Restricts outbound connections to only what's necessary
# Run as root on the host VPS

set -e

# Configuration - adjust these for your setup
WEBHOOK_DOMAINS="${WEBHOOK_DOMAINS:-}"  # Comma-separated list of allowed webhook domains
WG_PORT="${WG_PORT:-51820}"
WEB_PORT="${WEB_PORT:-3000}"
SSH_PORT="${SSH_PORT:-22}"

echo "=== PetalHop Egress Firewall Setup ==="
echo "WireGuard Port: $WG_PORT"
echo "Web Port: $WEB_PORT"
echo "SSH Port: $SSH_PORT"
echo "Webhook Domains: ${WEBHOOK_DOMAINS:-none}"

# Create nftables ruleset
cat > /tmp/petalhop-egress.nft << 'NFTEOF'
#!/usr/sbin/nft -f
# PetalHop Egress Firewall Rules
# Generated by egress-firewall.sh

# Flush existing egress rules (be careful not to lock yourself out!)
# We use a separate table to avoid conflicts with PetalHop's NAT rules

table inet petalhop_egress {
    chain output {
        type filter hook output priority 0; policy accept;

        # Allow loopback
        oif "lo" accept

        # Allow established/related (responses to incoming connections)
        ct state established,related accept

        # Allow DNS (UDP/TCP 53) - required for hostname resolution
        tcp dport 53 accept
        udp dport 53 accept

        # Allow NTP (UDP 123) - required for time sync
        udp dport 123 accept

        # Allow HTTPS outbound (TCP 443) - for webhooks
        # TODO: Restrict to specific IPs if you know your webhook server IPs
        tcp dport 443 accept

        # Allow HTTP outbound (TCP 80) - for Let's Encrypt ACME challenges
        tcp dport 80 accept

        # Allow ICMP (ping) - useful for debugging
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # Log and drop everything else
        # Uncomment to enable logging (can be noisy):
        # log prefix "EGRESS_DROP: " level warn

        # Default: accept (change to 'drop' for strict mode)
        # counter drop
    }

    chain input {
        type filter hook input priority 0; policy accept;

        # Allow loopback
        iif "lo" accept

        # Allow established/related
        ct state established,related accept

        # Allow SSH (adjust port if needed)
        tcp dport SSH_PORT_PLACEHOLDER accept

        # Allow WireGuard
        udp dport WG_PORT_PLACEHOLDER accept

        # Allow Web UI
        tcp dport WEB_PORT_PLACEHOLDER accept

        # Allow ICMP
        ip protocol icmp accept
        ip6 nexthdr icmpv6 accept

        # Drop invalid packets
        ct state invalid drop

        # Log and drop everything else
        # log prefix "INGRESS_DROP: " level warn
        # counter drop
    }
}
NFTEOF

# Replace placeholders with actual values
sed -i "s/SSH_PORT_PLACEHOLDER/$SSH_PORT/g" /tmp/petalhop-egress.nft
sed -i "s/WG_PORT_PLACEHOLDER/$WG_PORT/g" /tmp/petalhop-egress.nft
sed -i "s/WEB_PORT_PLACEHOLDER/$WEB_PORT/g" /tmp/petalhop-egress.nft

echo ""
echo "Generated nftables rules:"
echo "========================="
cat /tmp/petalhop-egress.nft

echo ""
echo "To apply these rules, run:"
echo "  nft -f /tmp/petalhop-egress.nft"
echo ""
echo "To make them persistent, add to /etc/nftables.conf"
echo ""
echo "WARNING: Test in a screen/tmux session first!"
echo "         You could lock yourself out if SSH is blocked."
echo ""

read -p "Apply rules now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Applying rules..."
    nft -f /tmp/petalhop-egress.nft
    echo "Rules applied. Testing SSH connection in 30 seconds..."
    echo "If you lose connection, rules will be flushed."

    # Safety: flush rules if no confirmation within 30 seconds
    (
        sleep 30
        if [ ! -f /tmp/petalhop-egress-confirmed ]; then
            echo "No confirmation received, flushing egress rules..."
            nft delete table inet petalhop_egress 2>/dev/null || true
        fi
    ) &

    read -p "Confirm rules are working (type 'yes'): " confirmation
    if [ "$confirmation" = "yes" ]; then
        touch /tmp/petalhop-egress-confirmed
        echo "Rules confirmed and active."

        # Save to persistent config
        read -p "Save to /etc/nftables.d/petalhop-egress.nft? (y/N) " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            mkdir -p /etc/nftables.d
            cp /tmp/petalhop-egress.nft /etc/nftables.d/petalhop-egress.nft
            echo "Saved. Add 'include /etc/nftables.d/*.nft' to /etc/nftables.conf"
        fi
    else
        echo "Flushing rules..."
        nft delete table inet petalhop_egress 2>/dev/null || true
        echo "Rules flushed."
    fi
else
    echo "Rules not applied. File saved at /tmp/petalhop-egress.nft"
fi
